### ISSUE TITLE
Pass `webpack.config.babel.js` to `karma-webpack`

### ISSUE THREAD

**Issue by feimosi** [webpack/karma-webpack#106]
Is there any way to pass `webpack.config.babel.js` written in ES2015 (ES6) to `karma-wepack` plugin? AFAIK you can't write karma.conf in ES6. So when I want to require my config it breaks on unknown syntax. It would be great if I could pass only the path to the config or if the plugin would use Webpack's default mechanism to detect configuration inside a project.

**Comment by lpil** [comment]
:+1:

**Comment by SimenB** [comment]
Just import `babel-register`, that's what webpack does under the hood

**Comment by feimosi** [comment]
Works fine. Thanks!
