### ISSUE TITLE
Tests don't run - 'bundle is now invalid' message

### ISSUE THREAD

**Issue by edoloughlin** [webpack/karma-webpack#11]
I've got a skeleton project with dummy tests in 14 files. It all builds in under four seconds. When I run my tests, PhantomJS times out (I've tried a timeout of up to a minute). I get the following output:

    DEBUG [config]: autoWatch set to false, because of singleRun
    DEBUG [plugin]: Loading karma-* from /usr/lib/node_modules
    DEBUG [plugin]: Loading plugin /usr/lib/node_modules/karma-chrome-launcher.
    DEBUG [plugin]: Loading plugin /usr/lib/node_modules/karma-firefox-launcher.
    DEBUG [plugin]: Loading plugin /usr/lib/node_modules/karma-jasmine.
    DEBUG [plugin]: Loading plugin /usr/lib/node_modules/karma-phantomjs-launcher.
    DEBUG [plugin]: Loading plugin /usr/lib/node_modules/karma-script-launcher.
    DEBUG [plugin]: Loading plugin /usr/lib/node_modules/karma-webpack-plugin.
    INFO [karma]: Karma v0.12.16 server started at http://localhost:8080/
    INFO [launcher]: Starting browser PhantomJS
    DEBUG [temp-dir]: Creating temp dir at /tmp/karma-71473708
    DEBUG [launcher]: /usr/lib/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs /tmp/karma-71473708/capture.js
    Hash: 7b59d5bd58888f0c4037
    Version: webpack 1.3.0-beta5
    Time: 9ms
    Asset  Size  Chunks       Chunk Names
    webpack: bundle is now VALID.
    webpack: bundle is now invalid.
    DEBUG [web-server]: serving: /usr/lib/node_modules/karma/static/client.html
    DEBUG [web-server]: serving: /usr/lib/node_modules/karma/static/karma.js
    DEBUG [web-server]: upgrade /socket.io/1/websocket/tltJALVffCGd34LjTcxd
    DEBUG [karma]: A browser has connected on socket tltJALVffCGd34LjTcxd
    INFO [PhantomJS 1.9.7 (Linux)]: Connected on socket tltJALVffCGd34LjTcxd with id 71473708
    DEBUG [launcher]: PhantomJS (id 71473708) captured in 0.631 secs
    WARN [PhantomJS 1.9.7 (Linux)]: Disconnected (1 times), because no message in 60000 ms.
    DEBUG [karma]: Run complete, exitting.
    DEBUG [launcher]: Disconnecting all browsers
    DEBUG [launcher]: Process PhantomJS exited with code 0
    DEBUG [temp-dir]: Cleaning temp dir /tmp/karma-71473708

I've seen that issue #8 is similar and was solved by increasing the timeout, but it doesn't work for me.

**Comment by farridav** [comment]
Hi @nmccready Im having the same issue, and im also using `HtmlWebpackPlugin`, did you manage to find a resolution?

**Comment by nmccready** [comment]
I can't remember if I made a PR or if it got shot down. Anyways the work is here https://github.com/realtymaps/karma-webpack and  https://github.com/nmccready/karma-webpack
