### ISSUE TITLE
Any reason for duplicate files in the Demo?

### ISSUE THREAD

**Issue by dmitriz** [webpack/karma-webpack#120]
Any reason for the first line as the same files are already included in the second?

``` js
'test/*_test.js': ['webpack'],
'test/**/*_test.js': ['webpack']
```

**Comment by d3viant0ne** [comment]
@dmitriz - From a JavaScript glob pattern perspective, no.

That could be some Webpack nuance related to entry points but I can't think of what that would be given how that glob pattern works.

**Comment by d3viant0ne** [comment]
@sokra Is there some Webpack nuance I am missing here in regards to the duplication or is this simply dated / incorrect information?

**Comment by d3viant0ne** [comment]
@dmitriz - The second will grab every file matching the pattern for the entire directory tree, the first obviously grabs just the `test/` directory.

It's more of a one or the other thing depending on if you have a nested test directory structure.
