### ISSUE TITLE
Wrong line numbers reported for errors

### ISSUE THREAD

**Issue by dmitriz** [webpack/karma-webpack#121]
I am getting seemingly wrong line numbers reported by karma:

```sh
Expected false to be truthy.
  at Object.<anonymous> (/Users/dmitrizaitsev/Repos/lodash-tests/tests/round_test.js:128:35)
Expected Function to be 0.1.
  at Object.<anonymous> (/Users/dmitrizaitsev/Repos/lodash-tests/tests/round_test.js:129:31)
```
where in fact the error generating lines are 82 and 83:

```js
// round_test.js
...
line 82:  expect(isFinite(roundCurried)).toBeTruthy()
line 83:  expect(roundCurried(0.13)).toBe(0.1)
```

Here are the lines from my `karma.conf.js`:
```js
...
 files: [
    'tests/**/*.js'
 ],
 preprocessors: {
   'tests/**/*.js': ['webpack']
 },
```

This is the repo to reproduce the mismatch:
https://github.com/dmitriz/lodash-tests/tree/number-mismatch

**Comment by dgsmith2** [comment]
Per the [README](https://github.com/webpack/karma-webpack#source-maps), have you tried adding the webpack preprocessor?

```javascript
preprocessors: {
    'tests/**/*.js': ['webpack', 'sourcemap']
},
```
Even though I am including it, the only time I get correct line numbers is when I debug the tests in Chrome (I haven't tried other browsers).

Related: #109, #104

**Comment by MikaAK** [comment]
Add ```
webpack: {
  // ...
  devtool: 'inline-source-map'
}
```
to karma or do similar in your webpack config
