### ISSUE TITLE
Phantomjs stall on webpack build

### ISSUE THREAD

**Issue by track0x1** [webpack/karma-webpack#131]
When PhantomJS uses webpack to build before running any tests, when it fails to find a file it stalls. This is causing issues on my build server which is hanging until I manually kill it.

`
12:02:23.598 Module not found: Error: Cannot resolve 'file' or 'directory' ...
`

Is there any solution to this? I already have `bail: true` in my webpack config for karma.

**Comment by d3viant0ne** [comment]
@track0x1 - Check #66 there are a couple of resolutions there for the bail issue.
