### ISSUE TITLE
keeps adding `/_karma_webpack_` to file paths?

### ISSUE THREAD

**Issue by grofit** [webpack/karma-webpack#136]
My build was working fine, and then when I sent it to travis I noticed that it blew up for some reason, anyway cleaned my node_modules and re installed and now for some reason I keep getting errors where it is saying the file does not exist, and is prefixing with `/_karma_webpack_`, so here is an example:

```
07 07 2016 10:00:58.013:ERROR [karma]: { [Error: no such file or directory]
  code: 'ENOENT',
  errno: 34,
  message: 'no such file or directory',
  path: '/_karma_webpack_/tests/specs/rules/max-value-rule-tests.ts' }
Error: no such file or directory
    at MemoryFileSystem.readFileSync (C:\Code\Web\treacherous\treacherous\node_modules\memory-fs\lib\MemoryFileSystem.js:114:10)
    at MemoryFileSystem.readFile (C:\Code\Web\treacherous\treacherous\node_modules\memory-fs\lib\MemoryFileSystem.js:297:21)
    at doRead (C:\Code\Web\treacherous\treacherous\node_modules\karma-webpack\index.js:156:26)
    at Plugin.readFile (C:\Code\Web\treacherous\treacherous\node_modules\karma-webpack\index.js:160:3)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

The file lives in `tests/specs/rules/max-value-rule-tests.ts` but no idea why it is looking there, my config looks like:

```
module.exports = function(config) {
    config.set({
        files: [
            'node_modules/bluebird/js/browser/bluebird.js',
            'tests/specs/**/*.ts'
        ],

        preprocessors: {
            'tests/specs/**/*.ts': ['webpack']
        },

        webpack: {
            module: {
                loaders: [
                    { test: /\.tsx?$/, loader: 'ts-loader', exclude: /node_modules/}
                ]
            },
            resolve: {
                extensions: ['.ts', '.js', '.tsx', '.jsx', '']
            }
        },

        frameworks: ['mocha'],

        // test result reporter
        reporters: ['progress'],

        // web server port
        port: 9876,

        // enable / disable colors in the output (reporters and logs)
        colors: true,

        // level of logging
        logLevel: config.LOG_INFO,

        // enable / disable watching file and executing tests whenever any file changes
        autoWatch: false,

        // start these browsers
        browsers: ['PhantomJS'],

        // Continuous Integration mode
        singleRun: true
    });
};
```

**Comment by d3viant0ne** [comment]
@grofit - Can you paste the os & node sections of your travis.yml?

i.e.
```
os:
  - linux
  - osx
node_js:
  - node
  - "6"
  - "5"
  - "4"
```

**Comment by goldhand** [comment]
@grofit I'm also wondering if adding an `output.path` to you your config would help. I think that `__karma_webpack__` is the default `output.path` and `output.publicPath`

**Comment by grofit** [comment]
I am pretty sure I fixed the issue whatever it was, given that I raised this a few weeks back I have completely forgotten the context as to what was actually happening. I didnt need to add output path but it all seems fine now, so just close it if needed.

**Comment by d3viant0ne** [comment]
@grofit - If you happen to remember, please append it to the issue

**Comment by boui** [comment]
Had the same trouble:
``
preprocessors: {
   ''tests/index.js': ['webpack'] // reported _karma_webpack_/tests/index,js could not be resolved
}
``
After setting up basePath in karma.conf it worked.
Out of plugin sources I do not see how output.publicPath can be helpful, but I put it there also just in case.

Hope that helps.
