### ISSUE TITLE
Is this abandonware?

### ISSUE THREAD

**Issue by necolas** [webpack/karma-webpack#138]
There hasn't been a new version published for a year

**Comment by bbottema** [comment]
The javascript world is moving fast and dependencies become fragile. It seems karma-webpack is unable to keep up.

**Comment by stevegibbings** [comment]
Maybe we can collaborate with the original owner to resolve any issues? It's open source after all and if we use it we should try to support it. I'm willing.

**Comment by d3viant0ne** [comment]
@necolas @bbottema @stevegibbings - As of this afternoon, all of the loaders have been assigned project leads and contributors to take the load off the webpack core team.

The karma-webpack lead is @MikaAK, I am one of the contributors that will be assisting Mika.

I have a bit of documentation to take care of in #139 and need to get our validation up to the webpack/webpack standard in #140 

As soon as that is complete, we will be working through the following in order.
- Existing pull requests
- Existing issues
- Release Tags

**Comment by stevegibbings** [comment]
@d3viant0ne great news. What's the best way I can assist?

**Comment by d3viant0ne** [comment]
It's really up to @MikaAK

That said, give us a few days to get the docs and code validations in place and I'm sure Mika will start sorting & prioritizing issues. That is probably going to be the point where community involvement is going to be most helpful. 

I just wanted to take a moment to comment as I was creating working tasks to assure everyone that we will be getting this loader squared away in short order.

**Comment by stevegibbings** [comment]
Understood and it's all appreciated. I'll support you guys wherever I can.

**Comment by bbottema** [comment]
Good to know this is still alive. Keep up the good work.

**Comment by necolas** [comment]
Good to hear. Thank you!
