### ISSUE TITLE
Add issue and pull request templates

### ISSUE THREAD

**Issue by d3viant0ne** [webpack/karma-webpack#139]
**Bring html-loader project documentation inline with webpack core**
- [x] Modify and add `ISSUE_TEMPLATE.md` from webpack/webpack
- [x] Modify and add `PULL_REQUEST_TEMPLATE.md` from webpack/webpack
- [x] Add LICENSE
- [x] Add CONTRIBUTING.md

**Comment by MikaAK** [comment]
I'm not quite sure what we want to do with support requests, having people open issues for support requests will probably cause clutter. What do you think?
cc @goldhand @DanielaValero @carlos-

**Comment by d3viant0ne** [comment]
Currently working on html-loader PR and I was just taking the stay inline with webpack.

In this particular case, webpack directs support requests to gitter / stackoverflow which I think is the right answer here as well.

Something to the effect of https://github.com/webpack/html-loader/pull/70/files

**Comment by goldhand** [comment]
Should these look like https://github.com/webpack/webpack/pull/2621/files ?

What kind of support request do you think will come in?

I think support requests for webpack 2.1.0-beta.X would be nice :smile:

@MikaAK there are a lot of issues. Can I go through them? Can I be added to a team so I can close or tag a few?

**Comment by d3viant0ne** [comment]
@goldhand - Check general in slack. Mika & I may have come up with ( borrowed from node ) a solution to support requests for the org that would benefit all of the loader / core teams.

**Comment by goldhand** [comment]
@d3viant0ne I'm waiting on an invite. Is there another way for my to join?

**Comment by d3viant0ne** [comment]
No, invite has to come from Sean. I'll mention it if I see him pop back online.

**Comment by d3viant0ne** [comment]
FYI - This is the template @michael-ciniawsky is proposing for all the loaders, I personally love it.

https://github.com/michael-ciniawsky/html-loader

**Comment by DanielaValero** [comment]
I particularly find very useful to have both templates, having them helps us to determine quicker what the bug is, or what the pull request is about. 

I also did not get the invite yet to slack, I guess Sam has been busy lately. See you there soon guys.
