### ISSUE TITLE
Travis execution inline with webpack/webpack

### ISSUE THREAD

**Issue by d3viant0ne** [webpack/karma-webpack#140]
**Bring karma-webpack travis execution inline with webpack core**
- [ ] Plan & author tests ( help wanted )
- [x] Add linting
- [ ] Add coverage generation / reporting via codecov.io

**Comment by d3viant0ne** [comment]
@MikaAK - https://codecov.io/gh/webpack/karma-webpack needs to be enabled by a member with write access.

**Comment by MikaAK** [comment]
@d3viant0ne it's enabled now!

**Comment by d3viant0ne** [comment]
Cheers :)
