### ISSUE TITLE
Code Quality tooling inline with webpack/webpack

### ISSUE THREAD

**Issue by d3viant0ne** [webpack/karma-webpack#142]
**Bring karma-webpack project code quality tooling inline with webpack core**
- [x] ESLint & Config
- [x] jsbeutify
- [x] editor config

**Comment by goldhand** [comment]
@TheLarkInn not sure where to ping you but I haven't received a slack invite for my email: __a.will.farley@gmail.com__

**Comment by d3viant0ne** [comment]
@goldhand - Already mentioned it to him, Tobias has to do it. Sean will mention it next time he's online.
