### ISSUE TITLE
possible timing problem: Error: no such file or directory

### ISSUE THREAD

**Issue by madebits** [webpack/karma-webpack#154]
I get an error up and now in the build server, which I do not have locally:

```
...
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
{ [Error: no such file or directory]
   code: 'ENOENT',
   errno: 34,
   message: 'no such file or directory',
   path: '/_karma_webpack_/test.js' }
 Error: no such file or directory
     at MemoryFileSystem.readFileSync (C:\PATH\node_modules\memory-fs\lib\MemoryFileSystem.js:114:10)
     at MemoryFileSystem.readFile (C:\PATH\node_modules\memory-fs\lib\MemoryFileSystem.js:297:21)
     at doRead (C:\PATH\node_modules\karma-webpack\index.js:156:26)
     at Plugin.readFile (C:\PATH\node_modules\karma-webpack\index.js:160:3)
     at C:\PATH\node_modules\karma-webpack\index.js:176:17
     at nextPreprocessor (C:\PATH\node_modules\karma\lib\preprocessor.js:35:26)
     at C:\PATH\node_modules\karma\lib\preprocessor.js:114:9
     at module.exports (C:\PATH\node_modules\isbinaryfile\index.js:28:12)
     at C:\PATH\node_modules\karma\lib\preprocessor.js:79:7
     at C:\PATH\node_modules\graceful-fs\graceful-fs.js:78:16
     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```

`test.js` file is there in disk, and inside `test.js` I use use `require.context` to load all `spec.ts` files in a folder.

As this error only happens sometimes in my build server and often a restart of build with same code state works, I suspect this can be some timing issue.

I looked at the failing code in `karma-webpack\index.js` inside `function createPreprocesor ...`. There if the file is not found the webpack bundle is invalidated:

```
if (webpackPlugin.addFile(file.path)) {
			// recompile as we have an asset that we have not seen before
			webpackPlugin.middleware.invalidate();
		}
```

After that the code there immediately tries to read the file:

```
// read blocks until bundle is done
webpackPlugin.readFile ...
```

Given that my file `test.js` uses `require.context` it may take some time for it to available in the memory file system used by the webpack middleware.

I am not sure, but I have the feeling changing the readFile code line to run within `waitUntilValid` would fix the error I face:

```
...
webpackPlugin.middleware.waitUntilValid(function(){
			// read blocks until bundle is done
			webpackPlugin.readFile(path.relative(basePath, file.path), function(err, content) {
				if (err) {
					throw err;
				}

				done(err, content && content.toString());
			});
		});
```

I tested this and it has no side effects that I can see in my case, but I do not know the webpack plugins so good to be sure this can really fix it. Can someone with more knowledge confirm whether my suspicion and fix are correct?

**Comment by d3viant0ne** [comment]
@madebits The issue I see with this approach would be the case where the bundle is actually invalid, in which case the new condition will never be true and blocks indefinitely. 

If you want to check for side effects, send it an invalid file path and see if it hangs. 

//cc @MikaAK @goldhand

**Comment by madebits** [comment]
@d3viant0ne Yes, what you says makes sense. The original sporadic timing issue remains thought, maybe one of you has a  better idea how to address this.

**Comment by madebits** [comment]
Update: Errors in files included by test.js may trigger the same error sometimes. The difference is that after the above error, the actual error is printed at some point. The situation I refer above is different from that, as it happens occasionally with same state of code when there no errors.

**Comment by protazy** [comment]
@madebits were you able to figure out what's wrong? I have the same issue. Does your workaround with retry help?

**Comment by madebits** [comment]
The workaround is wrong and does not help.

Everything in code looks ok, and I could not reproduce the error locally. But, I improved error handling in karma-webpack (not to crash the event loop around middleware.fileSystem.readFile usage in readFile) and used my own modfied version. I detect the errors and retry outside the plugin. This works for me, but it is not very clean, not generic, and I cannot share the code.

**Comment by protazy** [comment]
@madebits Ok, I see.
But why close the issue when it is not resolved yet?

**Comment by jrgleason** [comment]
I seem to be having similar issue I have the following...

```
var appFiles = globFlat.sync([
  './src/main/coffee/**/*.coffee',
]);
preprocessors: {
      './src/main/coffee/**/*.coffee': ['webpack'],
      ....
},
basePath: '',
```

And I get... 

```
17 10 2016 16:38:37.908:ERROR [karma]: { [Error: no such file or directory]
  code: 'ENOENT',
  errno: 34,
  message: 'no such file or directory',
  path: '/_karma_webpack_/src/main/coffee/utilities/view/ViewUtil.coffee' }
Error: no such file or directory
```

**Comment by jrgleason** [comment]
Also I have the entries and plugins removed. I am using split files.
