### ISSUE TITLE
SUT sourcemaps not working

### ISSUE THREAD

**Issue by ryanlangton** [webpack/karma-webpack#171]
Sourcemaps are not working for application files (System Under Test), while they work fine for the spec files themselves.

I've submitted a stackoverflow question, the suggested solution does not work.

http://stackoverflow.com/questions/39131809/karma-webpack-sourcemaps-not-working

**Comment by MikaAK** [comment]
Did you follow the instructions in the readme? Also the issue template is there for a reason this provides us no info.  Please feel free to reopen with the issue template
