### ISSUE TITLE
Less verbose logs

### ISSUE THREAD

**Issue by epegzz** [webpack/karma-webpack#181]
**I'm submitting a feature request**

**Webpack version:**
1.10.x/2.x

It would be nice having an option to have a less verbose log. To achieve this, the [`stats.JSON`](https://github.com/webpack/karma-webpack/blob/master/src/karma-webpack.js#L89) would require an [argument](https://webpack.github.io/docs/node.js-api.html#stats-tojson) which would need to be set via config.

**Comment by MikaAK** [comment]
You can set this in karma.config via 
```
webpackMiddleware: {
      // webpack-dev-middleware configuration
      // i. e.
      stats: 'errors-only'
},
```
