### ISSUE TITLE
Can not load "webpack" on Webpack@2.1.0-beta.26

### ISSUE THREAD

**Issue by wellyshen** [webpack/karma-webpack#182]
Hi Guys, I'am using the karma@1.3.0 with karma-webpack@1.8.0, currently I updating my webpack from 2.1.0-beta.25 to 2.1.0-beta.26, when I running npm test I encountered the following error, does anyone has the same issue?

Here's the error message :
<img width="828" alt="2016-11-15 10 18 32" src="https://cloud.githubusercontent.com/assets/21308003/20309068/81989978-ab81-11e6-98b6-1176e95bbc1f.png">

By the way here is my [repo](https://github.com/wellyshen/react-cool-starter)

**Comment by wellyshen** [comment]
The problem has been solved due to new [webpack external settings rule](https://webpack.js.org/configuration/externals/)

**Comment by DerZyklop** [comment]
I have the same issue. What did you do, to fix it? 

I found your `externals` settings here https://github.com/wellyshen/react-cool-starter/blob/master/tools/webpack/config.test.babel.js#L40-L45

You have some »react« stuff there. I tried this in my config, but it doesn’t change anything.

**Comment by d3viant0ne** [comment]
https://github.com/webpack-contrib/karma-webpack/releases/tag/v2.0.0

**Comment by DerZyklop** [comment]
?

If you tried to tell my that i should remove the `entry: {}` from my webpack config: I have no `entry: {}` in my webpack config.
