### ISSUE TITLE
Update webpack peerDependency with rc

### ISSUE THREAD

**Issue by TrySound** [webpack/karma-webpack#186]
**I'm submitting a bug report**

**Webpack version:**
2.2.0-rc.0

**Webpack Karma version**:
1.8

**Current behavior:**

PeerDependency failure

**Expected/desired behavior:**

exit 0

**Comment by DanielaValero** [comment]
Hello,
Would you also post the log ?

**Comment by TrySound** [comment]
npm3 and yarn only warn
```
npm WARN karma-webpack@1.8.0 requires a peer of webpack@^1.1.0 || ^2 || ^2.1.0-beta but none was installed.
```
```
[3/4] Linking dependencies...
warning Incorrect peer dependency "webpack@^1.1.0 || ^2 || ^2.1.0-beta".
```

Here's the npm2
```
npm WARN peerDependencies The peer dependency webpack@^1.1.0 || ^2 || ^2.1.0-beta included from 
npm ERR! Windows_NT 6.3.9600
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@2.2.0-rc.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer karma-webpack@1.8.0 wants webpack@^1.1.0 || ^2 || ^2.1.0-beta

npm ERR! Please include the following file with any support request:
npm ERR!     ***\npm-debug.log
```

**Comment by egoroof** [comment]
Have the same problem with npm2: https://travis-ci.org/egoroof/browser-id3-writer/jobs/185430258#L165
Could you release a new version after PR is merged, please?

**Comment by d3viant0ne** [comment]
Only @MikaAK has access to publish, given the holidays he may be on vacation. If I don't hear from him today, i'll get one of the core team members to publish a patch version.

**Comment by MikaAK** [comment]
I'll publish this today a I noticed this aswell
