### ISSUE TITLE
Cannot find module './lib/karma-webpack'

### ISSUE THREAD

**Issue by scottohara** [webpack/karma-webpack#197]
**I'm submitting a bug report**

**Webpack version:**
2.2.0-rc.3

**Webpack Karma version**:
2.0.0

**Karma version**:
1.1.1

**Please tell us about your environment:**
OSX 10.12.1

**Browser:**
Chrome 57

**Current behavior:**
1. Installed karma-webpack (`yarn add karma-webpack --dev`)
2. Configured `karma.conf.js` to run webpack preprocessor

```
preprocessors: {
  "test/**/*_test.js": ["webpack"]
},
```

3. Ran `karma start` in terminal
4. Received the following error:

```
12 01 2017 08:58:48.982:ERROR [plugin]: Error during loading "<path to project>/node_modules/karma-webpack" plugin:
  Cannot find module './lib/karma-webpack'
12 01 2017 08:58:48.988:ERROR [preprocess]: Can not load "webpack", it is not registered!
  Perhaps you are missing some plugin?
```

**Expected/desired behavior:**
karma should run without errors

Looking at the the contents of `/node_modules/karma-webpack/index.js`, the only line is:

`module.exports = require('./lib/karma-webpack')`

...however there is no `/node_modules/karma-webpack/lib` directory.

Should there be?

**Comment by d3viant0ne** [comment]
Yeah, package was published incorrectly. Pick up 2.0.1

**Comment by scottohara** [comment]
Thanks @d3viant0ne , confirming that 2.0.1 works perfectly.

Thanks for the super-quick response!
