### ISSUE TITLE
Missing changelog for version 2.x

### ISSUE THREAD

**Issue by blacksonic** [webpack/karma-webpack#199]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.28

**Webpack Karma version**:
2.0.1

**Karma version**:
1.3.0

**Please tell us about your environment:**
Linux, Ubuntu 16.04

**Browser:** PhantomJS

**Current behavior:**
Changelog is missing for new release, which can count as a breaking change: now Webpack config is validated and an empty `entry: {}` needs to be passed.

**Expected/desired behavior:**
Highlight breaking changes.

* **What is the motivation / use case for changing the behavior?**
Avoid surprises for upgraders.

**Comment by nickwaelkens** [comment]
And with `"webpack": "^2.2.0-rc.4"` that doesn't even work (anymore)? It can't be an empty object according to the `webpackOptionsSchema.json`.
Still trying to figure out how to set it up properly with 2.2.

**Comment by blacksonic** [comment]
@nickwaelkens it works for me with `"webpack": "2.2.0-rc.3"` and an empty object for `entry`.

**Comment by d3viant0ne** [comment]
https://github.com/webpack/karma-webpack/releases/tag/v2.0.0

I'll get the changelog fixed in a moment

**Comment by d3viant0ne** [comment]
@blacksonic @nickwaelkens - For rc.4 and forward remove the entry object entirely. 

> rc.4 enforces schema validation, passing an empty object will fail that validation. There is a bandaid ( bit of a hack tbh ) that will default `entry` to a function that returns an empty object if it doesn't exist in the config, this satisfies the schema validation for > rc.4

**Comment by d3viant0ne** [comment]
https://github.com/webpack/karma-webpack/blob/v2/CHANGELOG.md
