### ISSUE TITLE
exports is not defined error with Webpack 2.2.0-rc.5

### ISSUE THREAD

**Issue by farneman** [webpack/karma-webpack#203]
**I'm submitting a bug report**

**Webpack version:**
2.2.0-rc.5

**Webpack Karma version**:
2.0.1

**Karma version**:
1.4.9

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
My test suite was fully working with Webpack 2.2.0-rc.4. Upon updating to Webpack 2.2.0-rc.5 I'm getting an `Uncaught ReferenceError: exports is not defined.` error from any test file. 

**Expected/desired behavior:**
Test suite continues to run correctly with Webpack 2.2.0-rc.5 as it did with Webpack 2.2.0-rc.4.

I have a feeling this has to do with the breaking change in rc.5 which made module.exports return undefined. I've made no other changes on my end and my `.babelrc` file is set to use the ES2015 preset with `modules: false`.

**Comment by d3viant0ne** [comment]
@farneman - This should resolve itself one the PR lands with the fix in webpack. Currently just waiting on review.

**Comment by d3viant0ne** [comment]
@farneman - Just checked this with `webpack-rc.6` and all is well in the world of Karma again.
