### ISSUE TITLE
ERROR [preprocess]: Can not load "webpack"!

### ISSUE THREAD

**Issue by stevenfitzpatrick** [webpack/karma-webpack#207]
**I'm submitting a bug report**

**Webpack version:**
webpack@2.2.0-rc.3

**Webpack Karma version**:
2.0.1

**Karma version**:
1.4.0

**Please tell us about your environment:**
 Windows 10

**Browser:** PhantomJS 2.1.1

**Current behavior:**
Not working keep getting ERROR [preprocess]: Can not load "webpack"!

**Expected/desired behavior:**
Run Test

Current karma config looks like this

```
require('babel-register');
const webpack = require('../webpack.config.babel.js');
const path = require('path');
module.exports = function(config) {
  config.set({
    basePath: '../',
    frameworks: [ 'mocha', 'chai-sinon' ],
    browsers: [ 'PhantomJS' ],
    files: [ 'test/browser/**/*.js' ],
    preprocessors: {
      'test/**/*.js': [ 'webpack' ],
      'src/**/*.js': [ 'webpack' ]
    },
    webpack,
    webpackMiddleware: { noInfo: true }
  });
};
```

**Comment by stevenfitzpatrick** [comment]
Sorry you can close this one, was an error in my webpack config

**Comment by d3viant0ne** [comment]
![hook-em-horns](https://cloud.githubusercontent.com/assets/8420490/22003458/69b8f212-dc19-11e6-9624-84dfc83cec08.jpg)
