### ISSUE TITLE
Can not load 'webpack' - issue with v2.1.0

### ISSUE THREAD

**Issue by jpwiddy** [webpack/karma-webpack#210]
**I'm submitting a bug report**

**Webpack version:**
"webpack": "2.2.0-rc.1"

**Webpack Karma version**:
"karma-webpack": "1.8.0"

**Karma version**:
0.13.x/1.x

**Env**
OSX 10.x - Chrome Version 55.0.2883.95 (64-bit)

**Current behavior:**
Test runner fails out before getting to run step. Issue says 'Can not load "webpack"'

Project configuration: 

Currently using 
```
    "karma": "1.4.0",
    "karma-chrome-launcher": "2.0.0",
    "karma-coverage": "1.1.1",
    "karma-jasmine": "1.1.0",
    "karma-mocha-reporter": "2.2.1",
    "karma-phantomjs-launcher": "1.0.2",
    "karma-remap-coverage": "0.1.4",
    "karma-source-map-support": "1.2.0",
    "karma-sourcemap-loader": "0.3.7",
    "karma-webpack": "2.0.1"
```
with Webpack version specified above. Failing as follows:

```
keywords if/then/else require v5 option
18 01 2017 15:11:14.083:ERROR [preprocess]: Can not load "webpack"!
  Error
    at webpack (/Users/j/Developer/AspNetCoreSpa/node_modules/webpack/lib/webpack.js:17:9)
    at new Plugin (/Users/j/Developer/AspNetCoreSpa/node_modules/karma-webpack/lib/karma-webpack.js:65:18)
    at invoke (/Users/j/Developer/AspNetCoreSpa/node_modules/di/lib/injector.js:75:15)
    at Array.instantiate (/Users/j/Developer/AspNetCoreSpa/node_modules/di/lib/injector.js:59:20)
    at get (/Users/j/Developer/AspNetCoreSpa/node_modules/di/lib/injector.js:48:43)
    at /Users/j/Developer/AspNetCoreSpa/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/Users/j/Developer/AspNetCoreSpa/node_modules/di/lib/injector.js:70:31)
    at Injector.get (/Users/j/Developer/AspNetCoreSpa/node_modules/di/lib/injector.js:48:43)
    at instantiatePreprocessor (/Users/j/Developer/AspNetCoreSpa/node_modules/karma/lib/preprocessor.js:55:20)
    at Array.forEach (native)
    at createPreprocessor (/Users/j/Developer/AspNetCoreSpa/node_modules/karma/lib/preprocessor.js:74:20)
    at Array.invoke (/Users/j/Developer/AspNetCoreSpa/node_modules/di/lib/injector.js:75:15)
    at get (/Users/j/Developer/AspNetCoreSpa/node_modules/di/lib/injector.js:48:43)
    at /Users/j/Developer/AspNetCoreSpa/node_modules/di/lib/injector.js:71:14
    at Array.map (native)

START:
18 01 2017 15:11:14.154:INFO [karma]: Karma v1.4.0 server started at http://0.0.0.0:9876/
18 01 2017 15:11:14.154:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
18 01 2017 15:11:14.155:ERROR [karma]: Found 1 load error

npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/j/.nvm/versions/node/v7.4.0/bin/node" "/Users/j/.nvm/versions/node/v7.4.0/bin/npm" "run" "test"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! aspnetnetcore@0.0.0 test: `karma start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aspnetnetcore@0.0.0 test script 'karma start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the aspnetnetcore package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     karma start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs aspnetnetcore
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls aspnetnetcore
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/j/Developer/AspNetCoreSpa/npm-debug.log
```

Reverted to `"karma-webpack": "1.8.0"`, tests successfully run without warning.

**Comment by d3viant0ne** [comment]
Please try the same using Webpack `2.2.0` and we can go from there. IIRC that was an issue that went away with rc.3

**Comment by graingert** [comment]
I'm getting the issue with webpack 2.2.0 final:
with a debugger:

```js
(function (exports, require, module, __filename, __dirname) { /*
	MIT License http://www.opensource.org/licenses/mit-license.php
	Author Tobias Koppers @sokra
*/
"use strict";

const Compiler = require("./Compiler");
const MultiCompiler = require("./MultiCompiler");
const NodeEnvironmentPlugin = require("./node/NodeEnvironmentPlugin");
const WebpackOptionsApply = require("./WebpackOptionsApply");
const WebpackOptionsDefaulter = require("./WebpackOptionsDefaulter");
const validateSchema = require("./validateSchema");
const WebpackOptionsValidationError = require("./WebpackOptionsValidationError");
const webpackOptionsSchema = require("../schemas/webpackOptionsSchema.json");

function webpack(options, callback) {
	const webpackOptionsValidationErrors = validateSchema(webpackOptionsSchema, options);
	if(webpackOptionsValidationErrors.length) {
                debugger;
		throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
	}
```
and console.log(JSON.stringify(webpackOptionsValidationErrors));
I get:
```json
[{
	"keyword": "oneOf",
	"dataPath": ".entry",
	"schemaPath": "#/oneOf",
	"params": {},
	"message": "should match exactly one schema in oneOf",
	"schema": [{
		"minProperties": 1,
		"additionalProperties": {
			"oneOf": [{
				"description": "The string is resolved to a module which is loaded upon startup.",
				"minLength": 1,
				"type": "string"
			}, {
				"description": "All modules are loaded upon startup. The last one is exported.",
				"$ref": "#/definitions/common.nonEmptyArrayOfUniqueStringValues"
			}]
		},
		"description": "Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.",
		"type": "object"
	}, {
		"description": "The string is resolved to a module which is loaded upon startup.",
		"minLength": 1,
		"type": "string"
	}, {
		"allOf": [{
			"$ref": "#/definitions/common.nonEmptyArrayOfUniqueStringValues"
		}],
		"description": "All modules are loaded upon startup. The last one is exported."
	}, {
		"description": "function returning an entry object or a promise.",
		"instanceof": "Function"
	}],
	"parentSchema": {
		"description": "The entry point(s) of the compilation.",
		"oneOf": [{
			"minProperties": 1,
			"additionalProperties": {
				"oneOf": [{
					"description": "The string is resolved to a module which is loaded upon startup.",
					"minLength": 1,
					"type": "string"
				}, {
					"description": "All modules are loaded upon startup. The last one is exported.",
					"$ref": "#/definitions/common.nonEmptyArrayOfUniqueStringValues"
				}]
			},
			"description": "Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.",
			"type": "object"
		}, {
			"description": "The string is resolved to a module which is loaded upon startup.",
			"minLength": 1,
			"type": "string"
		}, {
			"allOf": [{
				"$ref": "#/definitions/common.nonEmptyArrayOfUniqueStringValues"
			}],
			"description": "All modules are loaded upon startup. The last one is exported."
		}, {
			"description": "function returning an entry object or a promise.",
			"instanceof": "Function"
		}]
	},
	"data": {},
	"children": [{
		"keyword": "minProperties",
		"dataPath": ".entry",
		"schemaPath": "#/oneOf/0/minProperties",
		"params": {
			"limit": 1
		},
		"message": "should NOT have less than 1 properties",
		"schema": 1,
		"parentSchema": {
			"minProperties": 1,
			"additionalProperties": {
				"oneOf": [{
					"description": "The string is resolved to a module which is loaded upon startup.",
					"minLength": 1,
					"type": "string"
				}, {
					"description": "All modules are loaded upon startup. The last one is exported.",
					"$ref": "#/definitions/common.nonEmptyArrayOfUniqueStringValues"
				}]
			},
			"description": "Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.",
			"type": "object"
		},
		"data": {}
	}, {
		"keyword": "type",
		"dataPath": ".entry",
		"schemaPath": "#/oneOf/1/type",
		"params": {
			"type": "string"
		},
		"message": "should be string",
		"schema": "string",
		"parentSchema": {
			"description": "The string is resolved to a module which is loaded upon startup.",
			"minLength": 1,
			"type": "string"
		},
		"data": {}
	}, {
		"keyword": "type",
		"dataPath": ".entry",
		"schemaPath": "#/definitions/common.nonEmptyArrayOfUniqueStringValues/type",
		"params": {
			"type": "array"
		},
		"message": "should be array",
		"schema": "array",
		"parentSchema": {
			"items": {
				"minLength": 1,
				"type": "string"
			},
			"minItems": 1,
			"type": "array",
			"uniqueItems": true
		},
		"data": {}
	}, {
		"keyword": "instanceof",
		"dataPath": ".entry",
		"schemaPath": "#/oneOf/3/instanceof",
		"params": {
			"keyword": "instanceof"
		},
		"message": "should pass \"instanceof\" keyword validation",
		"schema": "Function",
		"parentSchema": {
			"description": "function returning an entry object or a promise.",
			"instanceof": "Function"
		},
		"data": {}
	}]
}]
```

**Comment by graingert** [comment]
@d3viant0ne it looks like it's to do with:

```When updating to "webpack": "2.2.0-rc.4" & "karma-webpack": "1.8.2" you have to pull the entry property if it's set to an empty object so it defaults to a function within karma-webpack```

what does pull mean? Do you mean delete? in my config I don't have the entry property, but by the time it gets to the validate part it has gained a `entry: {}` property.

**Comment by graingert** [comment]
my bad, I was running karma-webpack 1.8 by mistake

**Comment by d3viant0ne** [comment]
@graingert - For webpack `2.2.0-rc.4` and beyond, config schema is strictly enforced and will error if it's missing something required.

As part of the schema enforcement, in you webpack configuration you can't pass `webpackConfig.entry` and empty object. Historically this has been a common practice in many test configs.

You can on the other hand pass `webpackConfig.entry` a function. So in the case where people were using `entry: {}` they simply need to remove it. For those that don't need / have an entry target in their config, removing it allows karma-webpack to use it's default which under the hood assigns a function that returns `entry: {}` to `webpackConfig.entry`.

**Comment by graingert** [comment]
@d3viant0ne yeah I know. I stepped through the code manually and found I was on the wrong code.

**Comment by d3viant0ne** [comment]
For the sake of clarity, are you good now or do we still have an issue that needs to be worked out with `webpack 2.2.0 / karma-webpack 2.0.1` ?

**Comment by graingert** [comment]
@d3viant0ne good to go. The documentation about "pull"ing .entry is not clear though. The versions are a bit out of date and "pull" isn't really the right term.

**Comment by d3viant0ne** [comment]
@graingert - I've updated the release notes: https://github.com/webpack/karma-webpack/releases/tag/v2.0.0

I'll get the same in the change log shortly

**Comment by jpwiddy** [comment]
👍  Thanks!

**Comment by DerZyklop** [comment]
I have the same issue and i can not find any `entry: {}` in my config files. 

I downgraded to `"karma-webpack@1.8.0"` and `webpack@^2.1.0-beta` but nothing changed.

In my webpack config there is this entry:

    entry: {
        app: [ path.resolve(rootDir, 'src', 'bootstrap') ],
        vendor: [ path.resolve(rootDir, 'src', 'vendor') ]
    },

...is this breaking it?

**Comment by graingert** [comment]
Yeah you can't have anything in your entry

**Comment by DerZyklop** [comment]
My fault. I was in the wrong config file. My webpack test config file has no `entry:` :/

**Comment by FDiskas** [comment]
same issue :taxi:

**Comment by zhanghaowx** [comment]
Same issue here,
"webpack": "^2.2.1",
"karma-webpack": "^2.0.2",

Downgrade my node from v7.7.2 to v6.10.0 gives me more info in console, so I see

    WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
    - configuration.module has an unknown property 'preLoaders'. These properties are valid:

After commenting out the preLoaders overwrite it works fine. Now I need to figure out how to get correct coverage report in webpack 2.0 ...

**Comment by napalm684** [comment]
I am getting the same issue with webpack 2.20 and karma-webpack 2.0.1:

`13 03 2017 16:17:44.469:ERROR [preprocess]: Can not load "webpack"!
  Error
    at webpack (C:\Spa.Client\node_modules\webpack\lib\webpack.js:19:9)
    at new Plugin (C:\Spa.Client\node_modules\karma-webpack\lib\karma-webpack.js:65:18)
    at invoke (C:\Spa.Client\node_modules\di\lib\injector.js:75:15)
    at Array.instantiate (C:\Spa.Client\node_modules\di\lib\injector.js:59:20)
    at get (C:\Spa.Client\node_modules\di\lib\injector.js:48:43)
    at C:\Spa.Client\node_modules\di\lib\injector.js:71:14
    at Array.map (native)
    at Array.invoke (C:\Spa.Client\node_modules\di\lib\injector.js:70:31)
    at Injector.get (C:\Spa.Client\node_modules\di\lib\injector.js:48:43)
    at instantiatePreprocessor (C:\Spa.Client\node_modules\karma\lib\preprocessor.js:55:20)
    at Array.forEach (native)
    at createPreprocessor (C:\Spa.Client\node_modules\karma\lib\preprocessor.js:74:20)
    at Array.invoke (C:\Spa.Client\node_modules\di\lib\injector.js:75:15)
    at get (C:\Spa.Client\node_modules\di\lib\injector.js:48:43)
    at C:\Spa.Client\node_modules\di\lib\injector.js:71:14
    at Array.map (native)
13 03 2017 16:17:44.514:INFO [karma]: Karma v1.5.0 server started at http://0.0.0.0:9876/
13 03 2017 16:17:44.517:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
13 03 2017 16:17:44.518:ERROR [karma]: Found 1 load error`

**Comment by napalm684** [comment]
Nevermind this was related to the other issue open hiding details of the webpack configuration errors rather than writing them to the console.

**Comment by gkohen** [comment]
@napalm684 , how can you diagnose what were the issues in the webpack configuration?

**Comment by FDiskas** [comment]
Add some console by editing node modules one by one :)

**Comment by napalm684** [comment]
@gkohen  go into the file for karma webpack add a try catch block around the webpack load and output errors to console in catch block.

**Comment by napalm684** [comment]
Line 65 karma-webpack.js of current master branch.

**Comment by gkohen** [comment]
Thanks folks. Ended up being, as expected a problem in my webpack config. It's a shame we can't turn on or propagate the errors to console from karma-webpack without editing the code.

**Comment by d3viant0ne** [comment]
@gkohen - I'm working on the karma-webpack eating errors problem now, should have most of the spots fixed in `2.0.4`

**Comment by gkohen** [comment]
@d3viant0ne , wicked cool. Thanks for this great component.

**Comment by kedar8** [comment]
karma problem to install: ERROR

 bpack-2.0.3.tgz"}},"2.0.4":{"name":"karma-webpack","version":"2.0.4" ,

To solve this error following command is useful for it. Its Solve for me...


_**npm cache clean --force**_
