### ISSUE TITLE
Producing a single test bundle

### ISSUE THREAD

**Issue by KidkArolis** [webpack/karma-webpack#23]
If I add `preprocessors: {'**/*_test.js': ['webpack']}` and I have 100s of tests, that produces 100s of large bundles - that's slow, reruns tests all the time since karma keeps detecting changes and rerunning all ests as each test bundle is produced by webpack and this sends many megabytes to the test browser to evaluate.

Instead, if I add `preprocessors: {"test_index.js": ['webpack']}` and require all my tests in that file ([e.g. here](https://github.com/QubitProducts/cherrytree/blob/master/test/index.js) then webpack produces 1 test bundle. However, now I have to manually maintain the full list of all my tests which doesn't scale.

I don't know enough about karma plugins or webpack yet, but do you reckon there's a way to configure webpack/karma/karma-webpack to produce ony 1 test bundle from a pattern such as `**/*_test.js`?

Perhaps something like dynamically, via the karma-webapck plugin, adding configuration about which modules to force include even if they're not required (is there such option?)

**Comment by damassi** [comment]
@plasticine, that `watch` update you made saved the day.  Went from 10+ seconds to compile on each change down to about 500ms :+1:

**Comment by plasticine** [comment]
> that watch update you made saved the day.

Awesome :D

**Comment by kentor** [comment]
Hmm I tried both `{ pattern: 'test/**/*_test.*', included: false, served: false, watched: true }` and adding `watch: true` to the webpack config. neither way detects a new test file for me

**Comment by damassi** [comment]
@kentor, the `watch` doesn't detect new files, but changes to existing files.

**Comment by jonira** [comment]
I'm having the following issue: ````karma start```` ends up with error: ````Uncaught ReferenceError: require is not defined```` for my test_index.js

**Comment by KidkArolis** [comment]
I had that issue yesterday..

Try upgrading karma, karma-webpack and webpack to the latest versions and
see if the issue persists. There was some breaking change somewhere
recently.

**Comment by jonira** [comment]
@KidkArolis thanks for the info. After I recreated the setup and installed latest packages, Karma started working.

**Comment by wbecker** [comment]
Had the same issue, think upgrading webpack to 1.11 from 1.10.5 solved the issue. Thanks Karo!

**Comment by tomazzaman** [comment]
I may be late to the party, but I come bearing gifts :)

The solution to this problem is to not use Karma at all (for unit tests that is). Or webpack for that matter. 

Here's the gist we use to run tests directly with Mocha: https://gist.github.com/tomazzaman/1e2c71e1afb6a45c1001

Save the file as `mocha-runner.js` and run it with `$ babel-node mocha-runner.js`

The gist is pretty well documented, so you shouldn't have any major problems understanding it.

**Comment by TotempaaltJ** [comment]
> I'm having the following issue: Karma detects file changes, but executes the old version of the file. Terminating and restarting karma causes the changed version of the file to be executed.

@jonira did you ever find a solution for this issue?

**Comment by robinelvin** [comment]
I have the same issue as @jonira had (and probably @TotempaaltJ too) in that changed files trigger the tests to reload but it executes the old code. I should add that my tests are written in Typescript and I don't see any output which tells me they are recompiled.

I'm using a test_index.js which pulls in all the .ts files as recommended.

Versions:
karma 1.3.0
karma-webpack 1.8.0
webpack 1.13.3

**Comment by Luchillo** [comment]
@robinelvin Same here, i have `karma-webpack` configured and it indeed doesn't recompile the tests.

Versions: 
karma 1.4.1
karma-webpack 2.0.2
webpack 2.2.0
