### ISSUE TITLE
Faster spec bundle preprocessing?

### ISSUE THREAD

**Issue by thomasboyt** [webpack/karma-webpack#3]
It takes a painful 60 seconds to compile my project's 45 spec files. Are there recommended ways of speeding this up? Not doing anything fancy, just using the boilerplate config from the README (including `cache: true`).

**Comment by mtscout6** [comment]
I've been running into the same problem lately with [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap). I'm not sure if any of the loaders I'm using are slow, is there a way to detect which loaders may be the culprit?

**Comment by d3viant0ne** [comment]
@thomasboyt @mtscout6 - Need to know if this is still an issue. For the sake of efficiency, we are starting with current versions and the team can work back from there. 

If this is still an issue on a recent version of the loader & it's peerDeps, please respond here so we can get this properly triaged.

**Comment by mtscout6** [comment]
Honestly I don't know if this is still an issue or not. @aabenoja may have more context on our project where we use this.

**Comment by d3viant0ne** [comment]
Closing this for now. Performance enhancements are planned once we get proper code validations in place.
