### ISSUE TITLE
1.4.0 causes ... has no method 'split' in karma-sourcemaps

### ISSUE THREAD

**Issue by tarjei** [webpack/karma-webpack#35]
Hi, I just upgraded to 1.4.0 and now I get the following error: 

You need to include some adapter that implements __karma__.start method!

If I use the plugin with the karma sourcemaps plugin I get a huge dump which at the end says that 
`Fatal error: Object /******/ (function(modules) { // webpackBootstrap           
  ...
]) has no method 'split'

Downgrading to 1.3.1 works. Any ideas why? 

I can provide a full list of my NPM dependencies if that is needed, but here are the main deps:

```
karma: 0.12.31
├── karma-sourcemap-loader@0.3.2
├─┬ karma-spec-reporter@0.0.13
├─┬ karma-webpack@1.4.0
├─┬ karma-webpack-plugin@1.0.0
│ └─┬ webpack-dev-middleware@1.0.6
├─┬ webpack@1.4.15
│ └─┬ webpack-core@0.4.8
└─┬ webpack-dev-server@1.6.5
  └─┬ webpack-dev-middleware@1.0.11
├── karma-sourcemap-loader@0.3.2
├─┬ karma-spec-reporter@0.0.13
├─┬ karma-webpack@1.4.0
├─┬ karma-webpack-plugin@1.0.0
│ └─┬ webpack-dev-middleware@1.0.6
├─┬ webpack@1.4.15
│ └─┬ webpack-core@0.4.8
└─┬ webpack-dev-server@1.6.5
  └─┬ webpack-dev-middleware@1.0.11
```

**Comment by mtscout6** [comment]
I see you have both `karma-webpack` and `karma-webpack-plugin`. I've been able to find the karma-webpack-plugin on npm, but I don't see it on github. What does this module do and why is can't it be included with karam-webpack?

**Comment by tarjei** [comment]
Hmm, I get the same error without the plugin as well.
 npm list |grep webp
├─┬ extract-text-webpack-plugin@0.3.6
├─┬ grunt-webpack@1.0.8
├─┬ karma-webpack@1.4.0
├─┬ webpack@1.4.15
│ └─┬ webpack-core@0.4.8
└─┬ webpack-dev-server@1.7.0
  └─┬ webpack-dev-middleware@1.0.11

**Comment by d3viant0ne** [comment]
@tarjei - Need to know if this is still an issue. For the sake of efficiency, we are starting with current versions and the team can work back from there.

If this is still an issue on a recent version of the loader & it's peerDeps, please respond here so we can get this properly triaged.

**Comment by tarjei** [comment]
Hi @d3viant0ne, thanks for reaching out.

I haven't seen this bug in quite a while so I will close this issue. I'm not sure if the bug is fixed or it is just I who have moved on[1].


1. I've been using karma-webpack-with-fast-source-maps for the last year or so - wish that could be imported into karma-webpack.

Regards,
Tarjei
