### ISSUE TITLE
code coverage

### ISSUE THREAD

**Issue by tadjik1** [webpack/karma-webpack#45]
Hello. Please help me to create code coverage report for my tests.
I'm trying to do this this way:

``` javascript
...
files: [
      'tests.webpack.js'
    ],

    preprocessors: {
      'scripts/**/*.js': ['webpack', 'sourcemap', 'coverage'],
      'tests.webpack.js': ['webpack', 'sourcemap', 'coverage']
    },

    reporters: ['progress', 'sourcemap', 'coverage'],

    webpack: {
      devtool: 'inline-source-map',
...    
```

but in /coverage folder i just see coverage of my tests.webpack.js file without sourcemaps!

So, what did I do wrong?

**Comment by gabel** [comment]
I've added an extended example Karma + Webpack + Mocha + Chai + Istanbul including coverage... you can have a look into https://github.com/gabel/karma-webpack-example

The preprocessor chain doesn't work out for me, thats why I used https://github.com/deepsweet/istanbul-instrumenter-loader.

**Comment by tadjik1** [comment]
@gabel Thank you very much! Very useful example. But what will you do when your js file would be transpiled via babel? I can not turn on sourcemaps for this situation.

**Comment by gabel** [comment]
Good question, it will probably need to run through webpack via loader instead of the karma preprocessor, but thats just guessing.

**Comment by d3viant0ne** [comment]
Need to know if this is still an issue. For the sake of efficiency, we are starting with current versions and the team can work back from there. 

If this is still an issue on a recent version of the loader & it's peerDeps, please respond here so we can get this properly answered.
