### ISSUE TITLE
Profiling

### ISSUE THREAD

**Issue by KidkArolis** [webpack/karma-webpack#47]
Any tips on how to get the profiling info out of the karma-webpack run?
Or otherwise inspect performance issues, the tests used to take 59 seconds to run with AMD, but 1 min 44 sec with webpack. It's ok for CI, but very unpleasant locally. Not sure how to speed it up.

Outside of testing, webpack takes 30seconds to build this project.

**Comment by KidkArolis** [comment]
In case of tests this 892 build out of which 295 are transpiled with babel.

**Comment by sokra** [comment]
Do you use the [alternative useage](https://github.com/webpack/karma-webpack#alternative-usage)?

**Comment by KidkArolis** [comment]
Yes. I think the test bundle takes 30-40 seconds to compile if I use babel. And 10 seconds without babel which is acceptable. Maybe this project is just too large, or maybe I shouldn't be always running all tests - but the latter is not easy with karma.

**Comment by KidkArolis** [comment]
I'm thinking about building another karma-webpack like plugin which allows a `--grep` arg to filter which test files get bundled. Is that of interest to anyone? :-"

**Comment by KidkArolis** [comment]
I think I managed to add some simple grepping via ContextReplacementPlugin

```js
// my test-main.js
var testsContext = require.context("../..", true, /_test$/);
testsContext.keys().forEach(testsContext);

// karma.config.js
...
if (argv.grep) {
    webpackConfig.plugins = _.union(webpackConfig.plugins, [
      new webpack.ContextReplacementPlugin(new RegExp('../..'), function (result) {
        result.regExp = new RegExp('.*' + argv.grep + '.*_test$');
      })
    ]);
  }
...
```

This allows me to run `karma start --grep foo` to filter some subset of tests to build with webpack, leaving full test runs to CI.

**Comment by mtscout6** [comment]
I just gave this a try and my test time increased by 2 seconds... Very odd.

**Comment by KidkArolis** [comment]
Perhaps that's the case for small sets of tests. For me, when I grep a small subset of tests, the time decreases from 2minutes to 15 seconds.

**Comment by KidkArolis** [comment]
I've just blogged about the `--grep` trick https://medium.com/@kidkarolis/karma-webpack-grep-super-fast-tests-in-dev-b11130e2c2c6 in case anyone's interested.

**Comment by larryhe** [comment]
Hi @KidkArolis nice post. I had a similar issue as yours due to our very large code base. Your post may solve our test problem. But I wonder how do you solve your incremental build issue (you should also have). I run webpack in watch mode, but whenever I change a file, it takes over 1 minute to compile&bundle which is way too long for developer.

**Comment by KidkArolis** [comment]
In my experience the incremental build is only slow if you use the wrong
sourcemap (devtool) option. Try them all to find the fast one..
