### ISSUE TITLE
Build not getting cancelled when webpack fails to compile the file

### ISSUE THREAD

**Issue by cedrics** [webpack/karma-webpack#49]
I am not really sure if this is an error with our configuration, `karma`, `karma-webpack` or `webpack` :smile: 

We are compiling `cjsx` (`coffee` and `jsx`) files using webpack and then run our tests using jasmine. Everything is working fine as long as you do not have a syntax error in your coffee file. At that point the tests just run using an outdated version of our code, which often means they just stay green :).
With webpack being quieted this does not result in any output and even if you output the error it can easily be overlooked because of the test run afterwards (which scrolls the error out of my terminal).

I would expect the tests to not be run and an error output to the displayed in karma.

Is this an issue that should be fixed here in the plugin or should this work out of the box and I am just too stupid to configure `karma-webpack`.

I already tried implementing this using [`failed`](http://webpack.github.io/docs/plugins.html#failed) callback of webpack. Is this the way to go here? I will try some more after work.

**Comment by marr** [comment]
have you tried the `bail` option in your webpack config? Also you can specify it in the cli: webpack --bail

**Comment by cedrics** [comment]
I did some more research yesterday (I forgot to do it initially) and as far as I can tell this is not really an issue of `karma-webpack`. We are using:

```
var testsContext = require.context(".", true, /_test$/);
testsContext.keys().forEach(testsContext);
```

To require all our specs and are using the `coffee` loader to precompile them. If the compilation of a spec fails the file is just ignored and the spec is therefore not run. When I require the file with a syntax error by hand (using `require`) the build gets cancelled. The `bail` option does not affect this behaviour as far as I can tell.

**Comment by yoni-tock** [comment]
I'm also having this issue. I guess one way to handle it would be to just specify all the tests individually...

**Comment by mroderick** [comment]
@cedrics did you find an elegant solution for this issue?

**Comment by cedrics** [comment]
Hi @mroderick, sadly I didn't. We are currently not working on the project using this setup and therefore did not run into the problem again and so I didn't spend anymore time on it / forgot all about it.

**Comment by mroderick** [comment]
@cedrics thanks

**Comment by marr** [comment]
Morgan,
Seems like the `bail` option in the webpack config is not being honored
properly according to this report
https://github.com/webpack/karma-webpack/issues/66.

**Comment by codazzo** [comment]
I've done some investigation on this and it appears that at least for me the chain of cause-and-effect is:

* Tests are required with the  [`require.context()` setup](https://github.com/webpack/karma-webpack/blob/1985f363e9cf39bdbcf2a15fadd3cbef98f341b9/example/test/index.js#L1-L2)
* Modules are therefore [marked as "optional"](https://github.com/webpack/webpack/blob/1b9e880f388f49bc88b52d5a6bbab5538d4c311e/lib/ContextModuleFactory.js#L113)
* The compilation step consequently marks the compilation with a [warning instead of an error](https://github.com/webpack/webpack/blob/1b9e880f388f49bc88b52d5a6bbab5538d4c311e/lib/Compilation.js#L221-L227)
* The bundle is successfully built
* The test in remaining files are run

Importing single test files with `require()` seems to fix the issue. I have yet to assess why `require.context` marks modules as "optional" and in that case whether it should be discouraged in use with karma-webpack.

**Comment by clouddra** [comment]
+1. Also encountering the same issue.

**Comment by Stuk** [comment]
Thanks for the insight into the optional modules and warnings, @codazzo. Based on that I wrote a mini webpack plugin that shows all warnings and then prevents the tests from running by pretending no assets were generated.

It's available at https://gist.github.com/Stuk/6b574049435df532e905 and can be simply added to your karma webpack config plugins.

Hope this helps people!

**Comment by pepaar** [comment]
@Stuk, with your plugin tests are not run but instead process with test run hangs (after showing warnings and before running tests). Is it possible to fail the test run instead?

**Comment by Stuk** [comment]
You may be able to replace the `stats.stats =` line with `throw new Error(...)` to get the process to exit with a failure.

I use this in watch mode, hence the waiting.

**Comment by pepaar** [comment]
That worked, thanks!

**Comment by mvgijssel** [comment]
I've created another plugin which also prevents Karma from hanging https://gist.github.com/mvgijssel/d3b121ad50e34c09a124

**Comment by d3viant0ne** [comment]
Closing this one, issue has multiple resolutions & the issue with karma-webpack not respecting `bail` is a known issue already on the hot list for the project team.

**Comment by icd2k3** [comment]
@mvgijssel that plugin fixed the issue for me - thanks!

**Comment by filipesilva** [comment]
I don't think this is the same as the bail issue. When running karma in watch mode it's troublesome to have karma report passing tests after fatal compilation errors. 

I'm using a variation of @Stuk's plugin myself, except I'm clearing the stats on errors instead of warnings. It blocks the compilation until I fix the errors. Only then does it re-run the tests in Karma.

**Comment by aldencolerain** [comment]
@d3viant0ne I don't think this issue should be closed or is resolved.  These plugins are workarounds.  Tests should not run/pass if the code doesn't build.  If your using karma start it will fail to build, karma's connection to the browser will timeout, and karma just sits there not exiting.

**Comment by jonesmac** [comment]
For those looking for a webpack v4 solution - https://gist.github.com/jonesmac/9ef456153c714db56be0ec24b61c6fbb

Seems to work for my use case but be interested to know if it works for others.

**Comment by tscislo** [comment]
For TypeScript it is sufficient to add to tsconfig.json

 "compilerOptions": {
   ...
    "noEmitOnError": true
  },

**Comment by thw0rted** [comment]
I'm using `noEmitOnError` and instead of failing, it just runs the last-built version of the test.  Might only work if you're not using the "alternate" (`require.context`-based) Karma config?

**Comment by TranquilMarmot** [comment]
We ended up using this with Webpack 5:

```ts
import { Compiler } from 'webpack';

/**
 * `karma-webpack` will just hang forever if there are compilation errors.
 * This plugin makes it so that the process actually ends with an error.
 */
export default class WebpackKarmaDieHardPlugin {
  public apply(compiler: Compiler) {
    compiler.hooks.failed.tap('WebpackKarmaDieHardPlugin', (error) => {
      console.error(error);
      process.exit(1);
    });
  }
}
```

Would it be possible to have `karma-webpack` detect failures and exit the process? It seems a little silly to have a plugin just to do this.

**Comment by marleypowell** [comment]
I got it to work by adding this to my `karma.conf.js` file:

```js
buildWebpack: {
  failureCb: () => {
    setTimeout(() => {
      process.exit(1);
    });
  },
},
```

`setTimeout` allowed the error logs to be displayed before exiting.
