### ISSUE TITLE
Webpack-dev-middleware semver broken AMD loading

### ISSUE THREAD

**Issue by chrisvxd** [webpack/karma-webpack#56]
The [`1.2.0` release](https://github.com/webpack/webpack-dev-middleware/releases/tag/v1.2.0) of [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware) has broken `karma-webpack` 1.5.1 and earlier when using AMD loading:

    ReferenceError: Can't find variable: define

Since `karma-webpack` is using minor dependency upgrades rather than patch, it automatically upgrades to `1.2.0`.

The simplest solution was to force downgrade `webpack-dev-middleware` to `1.0.11` in our root `package.json` (see https://github.com/rockabox/rbx_ui_components/pull/259), but perhaps `karma-webpack` should be using patch bumps rather than minor bumps (`^1.0.11` -> `~1.0.11`) or similar.

It could also be an issue in `webpack-dev-middleware`.

**Comment by nwhite89** [comment]
:+1:

**Comment by d3viant0ne** [comment]
//cc @MikaAK - Probably not a bad idea to tighten up the project deps as suggested.
