### ISSUE TITLE
gulp task never exits on CI

### ISSUE THREAD

**Issue by rsouthgate** [webpack/karma-webpack#57]
This seems like issue 18 but since that has been closed it may be environment specific or regression.

karma.conf.js:
```
'use strict';

module.exports = function(config) {

  var configuration = {
    
    autoWatch: false,
    singleRun: true,
    
    frameworks: ['jasmine'],

    browsers : ['PhantomJS'],

    plugins : [
      'karma-phantomjs-launcher',
      'karma-jasmine',
      'karma-webpack'
    ],
        
    preprocessors: {
      'test-harness.js': [ 'webpack']
    },
    
    files: [
      'test-harness.js'
    ],
    
    webpack: {
      module: {
        //loaders: [          
        //  { test: /\.ts$/, loader: "awesome-typescript-loader" }
        //]
      },
      resolve: {
        modulesDirectories: ["node_modules", "bower_components"],
        extensions: ['', '.webpack.js', '.web.js', '.ts', '.js']
      },
      watch: false
    },
    
    browserNoActivityTimeout: 100000,
   
  };

  config.set(configuration);
};
```
gulp task:
```
gulp.task('test', function(done) {
    karma.server.start({
      configFile: __dirname + '/../../karma.conf.js'//,
    }, function(exitCode) {
      console.log('Karma has exited with ' + exitCode);
      done(exitCode);
    });
  });

```
Note: I've commented out the loader fully expecting to get errors but I wanted to prove the loader wasn't holding onto the process. In this scenario I get errors reported from phantomJS but the task completes so I'd expect gulp to exit - however, it never returns me to the command prompt.
```
Karma has exited with 1
[08:40:23] 'test' errored after 1.3 min
```
If I uncomment the loader the tests complete succesfully and I get this:
```
Karma has exited with 0
[08:53:16] Finished 'test' after 1.35 min
```

**Comment by d3viant0ne** [comment]
@rsouthgate - Need to know if this is still an issue. For the sake of efficiency, we are starting with current versions and the team can work back from there. 

If this is still an issue on a recent version of the loader & it's peerDeps, please respond here so we can get this properly triaged.
