### ISSUE TITLE
TypeError: Object [object Object] has no method 'refreshFiles'

### ISSUE THREAD

**Issue by doombu** [webpack/karma-webpack#65]
seems your new release has broken our tests.

WARN [preprocess]: Can not load "webpack"!
TypeError: Object [object Object] has no method 'refreshFiles'

**Comment by alfrescian** [comment]
+1 - it's working fine with karma-webpack@1.6.0.

npm list --depth=0                                 
├── babel-core@5.8.19
├── babel-eslint@3.1.30
├── babel-loader@5.3.2
├── css-loader@0.14.5
├── eslint@0.22.1
├── eslint-loader@0.13.0
├── expose-loader@0.7.0
├── express@4.13.1
├── extract-text-webpack-plugin@0.8.2
├── file-loader@0.8.4
├── html-webpack-plugin@1.6.0
├── imports-loader@0.6.4
├── isparta-loader@0.2.0
├── json-loader@0.5.2
├── karma@0.12.37
├── karma-chrome-launcher@0.1.12
├── karma-coverage@0.4.2
├── karma-jasmine@0.2.3
├── karma-webpack@1.7.0
├── node-sass@3.2.0
├── path@0.11.14
├── raw-loader@0.5.1
├── sass-loader@1.0.3
├── style-loader@0.12.3
├── webpack@1.10.5
└── webpack-dev-middleware@1.2.0

**Comment by edvinerikson** [comment]
Solved it by updating Karma to `0.13.3` (and karma-webpack `1.7.0`).

**Comment by alfrescian** [comment]
thx! same here.

**Comment by gil** [comment]
Guys, shouldn't 1.7.0 be backwards compatible with 1.6.0 and only break with a major version update? I've cleaned node_modules, my project got updated today and it broke some production builds. I don't know if it's possible, but maybe a 1.7.1 update could fix the compatibility.

**Comment by gil** [comment]
I found the change and it seems to be easy to fix: https://github.com/webpack/karma-webpack/pull/63/files

I'm gonna travel in some hours but try to send a PR during the weekend.

**Comment by timmywil** [comment]
This issue seems to have resurfaced. I'm using karma-webpack@1.7.0 and karma@0.13.16.
