### ISSUE TITLE
Pass stats options to stats.toJson

### ISSUE THREAD

**Issue by kentcdodds** [webpack/karma-webpack#71]
In my excitement for [this](https://github.com/webpack/webpack/pull/1323) to be officially released, I attempted to use it with karma, but [it looks like](https://github.com/webpack/karma-webpack/blob/master/index.js#L64) karma-webpack isn't passing the stats options properly. I tried to implement it myself, but I think that for some reason I have two items in that stats array (stats are getting printed twice? not sure why).

Really looking forward to getting https://github.com/webpack/webpack/issues/1191 closed :-)

**Comment by dnutels** [comment]
@kentcdodds 

Would you mind sharing your config?

I am trying to see webpack output during testing with karma, but alas - only karma (and jasmine) messages show. Seems related to me.

**Comment by kentcdodds** [comment]
Hmmm... Seems like the opposite problem to me... I just add `webpackMiddleware: {noInfo: true}` to my `karma.conf.js` file and that seems to hide the webpack output.

**Comment by d3viant0ne** [comment]
@kentcdodds - This still an issue or can I tag and close it?

**Comment by kentcdodds** [comment]
Yeah, I haven't had any trouble for a while. Thanks.

**Comment by JimmyHoffa** [comment]
@kentcdodds you never did share how to pass the stats to webpack from karma, any clues??

**Comment by d3viant0ne** [comment]
@JimmyHoffa see https://github.com/webpack/webpack/pull/1323
