### ISSUE TITLE
Running tests alongside actual webpack build screws up output.

### ISSUE THREAD

**Issue by jeffijoe** [webpack/karma-webpack#72]
I am using Gulp with `webpack-stream`, and running the actual build of my app at the same time as my tests.

Doing so caused my bundled output file `main.js` to be named `main` without the `.js` extension.

I got around this by nulling the `output` property in my config for the tests.

```javascript
var webpackConfig = Object.assign({}, require('./build/webpack-config'), {
  stats: false,
  output: null // Fixes a Webpack issue where running the tests alongside the actual build would screw up the output.
});
```

Not sure how this happened. If you need any other info from me let me know.

**Comment by MattKunze** [comment]
This has been annoying me for a while as well - you end up with two stats listings for the webpack build, and the test one quickly scrolls past the main app output

Setting `stats: false` isn't working for me, once I have some time I'll see if I can track it down further

**Comment by d3viant0ne** [comment]
@jeffijoe @MattKunze - I'd need to see full configs as well as your gulp task to give you any useful information.

That said, if I had to guess I'd say you are watching from two different places || triggering from two different places || not waiting for the rebuild task to return before test execution if it's in a single gulp task.
