### ISSUE TITLE
The warning for the Alternative Usage is wrong

### ISSUE THREAD

**Issue by 0xR** [webpack/karma-webpack#87]
A couple of months ago I set up karma-webpack. Because of this warning: This configuration is more performant, but you cannot run single test anymore (only the complete suite). I chose to separate my test files from the code under test. Now I'm running into the issues because I have multiple bundles.

So in trying to find a solution I ignored the warning and used the more performant solution. As it turns out I can still run a single test :scream:. But even more importantly I have solved my issue. I run a single test by making it focused (fit / iit).

So my question is, what is the warning about? Being able to run only part of your code through webpack or something?

The problem I fixed by using a single bundle: I had created a separate bundle containing all the code under test. For each test I also created a bundle containing only the test and some imported domain classes from the production code. The issue that I now had the domain classes in both the test bundle and the production bundle. That caused instanceof checks to fail.

**Comment by d3viant0ne** [comment]
@0xR - If you don't mind this might be a good thing to outline in detail with a more descriptive title as your setup may be beneficial to others facing large test suites / performance issues.
