### ISSUE TITLE
Changes to files outside the require context are triggering re-compilation

### ISSUE THREAD

**Issue by evoyy** [webpack/karma-webpack#88]
I use Webpack's require context to select which files to bundle and execute.

````javascript
// tests.webpack.js
var context = require.context('.', true, /-test\.js$/);
context.keys().forEach(context);
````

I think this should mean that only files ending in "-test.js" should be included in the bundle and watched for changes. And in the karma config, I specify that webpack should do the watching:

````
module.exports = function(config) {
    config.set({
        basePath: '',
        frameworks: ['mocha'],
        files: [
            { pattern: 'tests.webpack.js', watched: false },
        ],
        plugins: [
            'karma-mocha',
            'karma-webpack',
        ],
        preprocessors: {
            'tests.webpack.js': [ 'webpack' ]
        },
        port: 9876,
        colors: true,
        logLevel: config.LOG_DEBUG,
        autoWatch: true,
        singleRun: false
    });
};
````

But webpack is also watching for new files, for example if I "touch somefile" the tests bundle is rebuilt and the test suite is run. This is a bit annoying because I am using vim and each time I edit a file, vim creates a temporary ".swp" file in the same directory. Any way to tell Webpack to not watch for new files?

**Comment by PerlPong** [comment]
Found a workaround by disabling vim swap files. Closing issue for now.

**Comment by graingert** [comment]
@evoyy I'm currently having this issue, can you re-open?

**Comment by graingert** [comment]
My tests/tests.js is now:

```javascript
const testsContext = require.context('.', true, /^\.\/([^/]+\/)*(([^/.])[^/]*)?\_test$/);
testsContext.keys().map(testsContext);
```

**Comment by graingert** [comment]
Which should ignore files like `./path/to/.Foo_test.es2015.js.swp` but it still reloads

**Comment by d3viant0ne** [comment]
@graingert - Checking your regex against that file, it's doesn't match that string or any portion of it

For reference, verifying RegEx the easy way - http://regexr.com/
