### ISSUE TITLE
Question: TypeScript entry point 

### ISSUE THREAD

**Issue by claycephas** [webpack/karma-webpack#89]
Is it possible to point karma at .ts files for the tests or must it be a .js file that requires the .ts files?

**Comment by Zorgatone** [comment]
:+1:

**Comment by wub** [comment]
+1

**Comment by ppoliani** [comment]
What I usually do in this situation is 

    ....
    files: [
            "client/specs/index.ts",
            "client/specs/**/*spec.ts"
    ],

    webpack: {   
     module: {
                noParse: [
                ],

                loaders: [
                    {
                        test: /\.ts(x?)$/,
                        exclude: /node_modules/,
                        loader: "babel-loader" +
                                "?presets[]=es2015&presets[]=react" +
                                "&plugins[]=syntax-async-functions" +
                            "!ts-loader"

                    }
                ]
            }
    }
    ...

That's what the files porperty look like in the `karma.conf` file.

**Comment by claycephas** [comment]
Ok, I got it working. Thanks!

karma.conf

    ...
    files: ["specs.ts"],
    preprocessors: {
      "specs.ts": ["webpack", "sourcemap"]
    },
    webpack: {
      devtool: "inline-source-map",
      resolve: {
        extensions: ["", ".ts", ".js"]
      },
      module: {
        loaders: [
          { test: /\.ts$/, loader: "ts-loader" },
          { test: /\.html$/, loader: "raw" },
          { test: /\.(jpg|png|woff|woff2|eot|ttf|svg|scss)$/, loader: "null" },
        ]
      }
    },
    ...

specs.ts

    import "angular";
    import "angular-mocks";
    import "./thing1.spec.ts";
    import "./thing2.spec.ts";

**Comment by jusefb** [comment]
I have tried this, and the test run however the report does not show where the error originates from. It is almost like the sourcemap only goes one level deep:

test.ts is my main entry file that loads all other typescript files.

Expected undefined to be 'some_random_token'.
	    at SafeSubscriber._next (_sadie_client/test.ts:65560:42)
	    at SafeSubscriber.__tryOrSetError (_sadie_client/test.ts:1639:16)
	    at SafeSubscriber.next (_sadie_client/test.ts:1581:27)
	    at Subscriber._next (_sadie_client/test.ts:1532:26)

Any ideas?

**Comment by donvadicastro** [comment]
The same behavior. How to point to *.ts or even transpiled *.js file where error occurs?

**Comment by jusefb** [comment]
Somehow the angular-cli manages to do it but I am not sure if it uses karma-webpack to transpile the typescript code. I am using angular-cli for now to run my tests but appreciate if someone could help in understanding what should be the correct configuration to make this work.

**Comment by jusefb** [comment]
Yes, very interested in getting this to work. Have been battling with the karma file for hours and still no luck
