### ISSUE TITLE
Plugins that generate assets cause karma-webpack to fail

### ISSUE THREAD

**Issue by Stuk** [webpack/karma-webpack#90]
I have a plugin that always generates a version file asset. It seems that karma-webpack checks to see if any assets exist, and if so then runs the tests. In this case the version file exists but the test bundle doesn't, and so karma-webpack fails with:

```
Fatal error: Path doesn't exist '/_karma_webpack_/test/config/tests.webpack.js'
```

**Comment by goldhand** [comment]
@Stuk can you provide an example of the plugin you are using? Is this still an issue or did you find a work-around?

**Comment by d3viant0ne** [comment]
@goldhand - This is related to a `node 4.1.x / npm` version. See #86

**Comment by goldhand** [comment]
@d3viant0ne is this related to #136 and #124 too? Is the `_karma_webpack_` being added because the webpack config has no output.path described?

Looks like the default path is [`__karma_webpack__`](https://github.com/webpack/karma-webpack/blob/24628dcb9bc30d2b6b5a2df94f3e8fc9cd5bf278/index.js#L43)
