### ISSUE TITLE
Module build failed, Invalid Mapping

### ISSUE THREAD

**Issue by r4d1n** [webpack/karma-webpack#93]
While upgrading my project to use Babel 6, I am seeing this error when running karma with the webpack loader. It builds and runs fine when not testing. (I've subbed out some of the specific names of files/paths here).

`Module build failed: Error: {HOME}/{PROJECT-PATH}/node_modules/babel-loader/index.js?{"plugins":["transform-runtime"]}!/{HOME}/{PROJECT-PATH}/test/browser/makeChart.spec.js: Invalid mapping: {"generated":{"line":null,"column":null,"lastColumn":null},"source":"{HOME}/{PROJECT-PATH}/test/browser/{MODULE}.spec.js","original":{"line":1,"column":0},"name":null}`

The stack trace leads back to the babel loader, however since this is only happening when trying to run tests I think my problem has to do with the way I've set up my tests/karma/webpack. 

My webpack config:

```javascript

var path = require('path');
var webpack = require('webpack');

module.exports = {
  cache: true,
  entry: [
    'babel-polyfill',
    './client/js/index.js'
  ],
  output: {
    path: path.join(__dirname, 'dist'),
    publicPath: 'dist/',
    filename: 'bundle.js',
    chunkFilename: '[chunkhash].js'
  },
  module: {
    loaders: [
      { test: /\.json$/, loader: 'json' },
      { test: /\.css$/, loader: 'style!css' },
      { test: /\.scss$/, loader: 'style!css!autoprefixer!sass!' },
      {
        test: /\.js$/,
        loader: 'babel',
        exclude: /node_modules/,
        query: {
          plugins: ['transform-runtime']
        }
      },
      {
        test: /\.spec.js$/,
        loader: 'babel',
        query: {
          plugins: ['transform-runtime']
        }
      }
    ]
  },
  plugins: [
    new webpack.ProvidePlugin({
      _: 'lodash',
      Logger: 'js-logger'
    })
  ],
  devtool: 'inline-source-map'
};
```

and karma.conf.js: 

```javascript
var webpackConfig = require('./webpack.config');
webpackConfig.devtool = 'inline-source-map';

module.exports = function(config) {
  config.set({

    webpack: webpackConfig,

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',


    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['mocha'],


    // list of files / patterns to load in the browser
    files: [
      'test/browser/tests.bundle.js'
    ],

    client: {
      mocha: {
        reporter: 'html',
        ui: 'tdd'
      }
    },

    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
      'test/browser/tests.bundle.js': ['webpack', 'sourcemap']
    },

    plugins: [
      'karma-webpack',
      'karma-mocha',
      'karma-chai',
      'karma-sourcemap-loader',
      'karma-chrome-launcher'
    ],

    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress'],


    // web server port
    port: 9876,

    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['Chrome'],


    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false
  })
}
```
My client-side tests are all in one directory together with names like module.spec.js. The 'test/browser/tests.bundle.js' mentioned in the karma config contains: 

```javascript
var context = require.context('.', true, /.+\.spec\.js?$/);
context.keys().forEach(context);
module.exports = context;`
```

Any help or suggestions would be much appreciated as I have had limited luck searching so far. Thanks for making this project.

**Comment by r4d1n** [comment]
I fixed this by not loading my .spec.js files separately from the rest of the .js files in webpack. Prior to using Babel 6 it had worked this way, but now it was causing  this problem.

**Comment by mmahalwy** [comment]
howd you find your output file? How'd you debug this?

**Comment by r4d1n** [comment]
That output was what printed to my console when I tried to run the tests. 

At the moment I can't remember exactly what my thought process was that led to the fix. I just tried a bunch of different things to troubleshoot and eventually realized the spec files were potentially being processed twice.
