### ISSUE TITLE
Running just one test

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack/karma-webpack#98]
Would it be possible to adjust this plugin so that it may only load one test? Basically:

``` javascript
// Pseudo code.
if(cliOptions.has("this-test") && patternMatches(config.preprocessors, cliOptions.get("this-test"))) {
    config.files = [cliOptions.get("this-test")]
} else throw new Error("Specified test does not match anything");
```

Going back and forth changing code and maybe accidentially committing is rather annoying. Having a commandline switch would be way more convenient.

**Comment by lior-a** [comment]
Meanwhile if someone want to run a single file from the terminal, I open PR with example on how to config your karma-webpack:
https://github.com/webpack/karma-webpack/pull/178

Than you can run from the terminal:
`npm test --single_file=**/my-specific-spec.js`
